package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The type Finestra aggiungi societa.
 */
public class finestraAggiungiSocieta {
    private JPanel panel;
    private JButton buttonOK;
    private JTextField textNomeSocieta;
    private JTextField textValoreAzione;
    /**
     * The Frame chiamante.
     */
    public JFrame frameChiamante;
    /**
     * The Frame.
     */
    public JFrame frame;
    /**
     * The Controller.
     */
    public Controller controller;
    private JPanel panelInput;
    private JLabel labelNomeSocieta;
    private JLabel labelValoreAzione;

    /**
     * Instantiates a new Finestra aggiungi societa.
     *
     * @param frameChiamante the frame chiamante
     * @param controller     the controller
     */
    public finestraAggiungiSocieta(JFrame frameChiamante, Controller controller) {

        this.frameChiamante = frameChiamante;
        this.controller = controller;
        frame = new JFrame("Seconda Finestrs");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        buttonOK.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String nomeSocieta = textNomeSocieta.getText();
                String valoreAzione = textValoreAzione.getText();
                if (nomeSocieta.equals("") || valoreAzione.equals("")) {
                    JOptionPane.showMessageDialog(null, "Inserisci tutti i campi");
                    return;
                }
                float valoreAzioneFloat;
                try {
                    valoreAzioneFloat = Float.parseFloat(valoreAzione);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Inserisci un valore numerico per il valore azione");
                    return;
                }
                boolean inserimentoOK = controller.addSocieta(nomeSocieta, valoreAzioneFloat);
                if (inserimentoOK) {
                    JOptionPane.showMessageDialog(null, "Società inserita correttamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Società già presente");
                }
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInput = new JPanel();
        panelInput.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(panelInput);
        labelNomeSocieta = new JLabel();
        labelNomeSocieta.setText("Nome Societa");
        panelInput.add(labelNomeSocieta, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panelInput.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        labelValoreAzione = new JLabel();
        labelValoreAzione.setText("Valore Azione");
        panelInput.add(labelValoreAzione, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textNomeSocieta = new JTextField();
        panelInput.add(textNomeSocieta, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textValoreAzione = new JTextField();
        panelInput.add(textValoreAzione, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(panel1);
        buttonOK = new JButton();
        buttonOK.setText("OK");
        panel1.add(buttonOK);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
