package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The type Finestra acquista azione.
 */
public class FinestraAcquistaAzione {
    private final JFrame frameChiamante;
    private final Controller controller;
    /**
     * The Frame.
     */
    public JFrame frame;
    private JPanel panel;
    private JComboBox comboBoxSocieta;
    private JTextField textNumeroAzioni;
    private JButton buttonOK;
    private JLabel labelNomeSocieta;
    private JLabel labelNumeroAzioni;

    /**
     * Instantiates a new Finestra acquista azione.
     *
     * @param frameChiamante the frame chiamante
     * @param controller     the controller
     */
    public FinestraAcquistaAzione(JFrame frameChiamante, Controller controller) {
        this.frameChiamante = frameChiamante;
        this.controller = controller;
        this.frame = new JFrame("Seconda Finestrs");
        this.frame.setContentPane(panel);
        this.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.frame.pack();

        //popola la combobox
        for (String nomeSocieta : controller.getNomiSocieta()) {
            comboBoxSocieta.addItem(nomeSocieta);
        }
        this.frame.setVisible(true);

        buttonOK.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String nomeSocieta = (String) comboBoxSocieta.getSelectedItem();
                String numeroAzioni = textNumeroAzioni.getText();
                if (numeroAzioni.equals("")) {
                    JOptionPane.showMessageDialog(null, "Inserisci tutti i campi");
                    return;
                }
                int numeroAzioniInt;
                try {
                    numeroAzioniInt = Integer.parseInt(numeroAzioni);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Inserisci un valore numerico per il numero di azioni");
                    return;
                }
                boolean inserimentoOK = controller.acquistaAzione(nomeSocieta, numeroAzioniInt);
                if (inserimentoOK) {
                    JOptionPane.showMessageDialog(null, "Azione acquistata correttamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Azione non acquistata");
                }
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        labelNomeSocieta = new JLabel();
        labelNomeSocieta.setText("Nome Societa");
        panel.add(labelNomeSocieta, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboBoxSocieta = new JComboBox();
        panel.add(comboBoxSocieta, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelNumeroAzioni = new JLabel();
        labelNumeroAzioni.setText("Numero Azioni");
        panel.add(labelNumeroAzioni, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textNumeroAzioni = new JTextField();
        panel.add(textNumeroAzioni, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        buttonOK = new JButton();
        buttonOK.setText("OK");
        panel.add(buttonOK, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
