package gui;

import controller.Controller;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * The type Lista societa.
 */
public class ListaSocieta {
    /**
     * The Frame chiamante.
     */
    public JFrame frameChiamante;
    /**
     * The Frame.
     */
    public JFrame frame;
    private JPanel panel;
    private JButton buttonToHome;
    private JTable table1;

    private Controller controller;

    /**
     * Instantiates a new Lista societa.
     *
     * @param frameChiamante the frame chiamante
     * @param controller     the controller
     */
    public ListaSocieta(JFrame frameChiamante, Controller controller) {
        this.frameChiamante = frameChiamante;
        this.controller = controller;
        frame = new JFrame("Listino Societa");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        buttonToHome.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
        table1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        DefaultTableModel tableModel = new DefaultTableModel(new Object[][]{}, new String[]{"Societa", "Valore Azione"});
        table1.setModel(tableModel);
        //table1.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Societa", "Valore Azione"}));
        //DefaultTableModel tableModel = (DefaultTableModel) table1.getModel();
        // leggiamo tramite il controller le liste di nomi societa e valori azioni
        ArrayList<String> listaNomiSocieta = controller.getNomiSocieta();
        ArrayList<Float> listaValoriAzione = controller.getValoriAzione();
        if (listaNomiSocieta != null) {
            for (int i = 0; i < listaNomiSocieta.size(); i++)
                //riempiamo il model che mostrerà i valori sullo schermo
                tableModel.addRow(new Object[]{listaNomiSocieta.get(i), listaValoriAzione.get(i)});

        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.setMinimumSize(new Dimension(123, 500));
        table1 = new JTable();
        table1.setAutoCreateRowSorter(true);
        table1.setFillsViewportHeight(true);
        panel.add(table1);
        buttonToHome = new JButton();
        buttonToHome.setText("Return");
        panel.add(buttonToHome);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
